// Họ vần của task 27, phần 2: 26 họ ngoài bốn họ đã viết ở families.ts (-at, -ir, -ake, -ight). Từ chưa có trong kho thì nằm ở prisma/seed/wordlab/family-words.json.
// Sinh bằng bảng mô tả duy nhất rồi chỉnh tay; mọi họ ở trạng thái Nháp cho tới khi đoạn văn vui có giọng đọc và người dùng xuất bản.
import type { FamilySeedEntry } from "../word-family-data.ts";

export const FAMILIES_WORDLAB_MORE: FamilySeedEntry[] = [
  {
    pattern: "an",
    soundIpa: "/æn/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "g", "j"],
    trapNote: "Từ woman cũng có chữ “an” nhưng đọc là /ˈwʊmən/, không phải âm /æn/ như cả họ. Nghe kỹ nhé!",
    members: ["man", "van", "can", "fan", "pan", "ran"],
    traps: ["woman"],
    sentences: [
      { en: "The man has a fan and a pan.", vi: "Người đàn ông có một cái quạt và một cái chảo." },
      { en: "He can run with the pan.", vi: "Ông ấy có thể chạy với cái chảo." },
    ],
  },
  {
    pattern: "ad",
    soundIpa: "/æd/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "Hai từ này cũng có chữ “ad” nhưng đọc là /ed/: head đọc là /hed/, bread đọc là /bred/. Nghe kỹ nhé!",
    members: ["dad", "sad", "bad", "mad", "pad", "glad"],
    traps: ["head", "bread"],
    sentences: [
      { en: "Dad is sad and mad.", vi: "Bố buồn và giận." },
      { en: "I am glad to give Dad a pad.", vi: "Tôi vui vì tặng bố một tập giấy." },
    ],
  },
  {
    pattern: "en",
    soundIpa: "/en/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "Hai từ này cũng có chữ “en” nhưng ở cuối từ đọc nhẹ là /ən/: open đọc là /ˈəʊpən/, listen đọc là /ˈlɪsən/. Nghe kỹ nhé!",
    members: ["hen", "ten", "pen", "men", "den", "when"],
    traps: ["open", "listen"],
    sentences: [
      { en: "Ten men and a hen are in the den.", vi: "Mười người đàn ông và một con gà mái ở trong hang." },
      { en: "When the hen sees a pen, it runs.", vi: "Khi con gà mái nhìn thấy cây bút, nó chạy mất." },
    ],
  },
  {
    pattern: "et",
    soundIpa: "/et/",
    levelNumber: 3,
    buildRime: null,
    decoys: ["z", "k", "d"],
    trapNote: "Từ sweet cũng có chữ “et” nhưng đọc là /swiːt/, không phải âm /et/ như cả họ. Nghe kỹ nhé!",
    members: ["net", "vet", "get", "wet", "pet", "jet", "set"],
    traps: ["sweet"],
    sentences: [
      { en: "The vet has a wet pet.", vi: "Bác sĩ thú y có một con thú cưng bị ướt." },
      { en: "My pet can get a net.", vi: "Thú cưng của tôi có thể lấy một cái lưới." },
    ],
  },
  {
    pattern: "ig",
    soundIpa: "/ɪɡ/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "h"],
    trapNote: "",
    members: ["pig", "big", "dig", "wig", "fig"],
    traps: [],
    sentences: [
      { en: "The big pig has a wig.", vi: "Con lợn to có một bộ tóc giả." },
      { en: "It can dig and eat a fig.", vi: "Nó biết đào đất và ăn quả sung." },
    ],
  },
  {
    pattern: "in",
    soundIpa: "/ɪn/",
    levelNumber: 2,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "Hai từ này cũng có chữ “in” nhưng đọc là /eɪn/: rain đọc là /reɪn/, train đọc là /treɪn/. Nghe kỹ nhé!",
    members: ["chin", "thin", "win", "skin", "bin", "pin", "tin"],
    traps: ["rain", "train"],
    sentences: [
      { en: "Put a pin in the tin bin.", vi: "Hãy bỏ một cái ghim vào thùng thiếc." },
      { en: "The thin man has a pin on his chin.", vi: "Người đàn ông gầy có một cái ghim trên cằm." },
    ],
  },
  {
    pattern: "ip",
    soundIpa: "/ɪp/",
    levelNumber: 3,
    buildRime: null,
    decoys: ["v", "g", "j"],
    trapNote: "",
    members: ["ship", "trip", "lip", "hip", "tip", "zip", "sip"],
    traps: [],
    sentences: [
      { en: "I sip juice on a ship trip.", vi: "Tôi nhấp nước ép trong chuyến đi tàu." },
      { en: "Then I zip my bag.", vi: "Rồi tôi kéo khóa cặp lại." },
    ],
  },
  {
    pattern: "it",
    soundIpa: "/ɪt/",
    levelNumber: 2,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "Từ fruit cũng có chữ “it” nhưng đọc là /fruːt/, không phải âm /ɪt/ như cả họ. Nghe kỹ nhé!",
    members: ["sit", "fit", "hit", "bit", "kit", "pit"],
    traps: ["fruit"],
    sentences: [
      { en: "I sit and eat a bit of fruit.", vi: "Tôi ngồi và ăn một chút trái cây." },
      { en: "Then I hit the ball with my kit.", vi: "Rồi tôi đánh bóng bằng bộ đồ của mình." },
    ],
  },
  {
    pattern: "ick",
    soundIpa: "/ɪk/",
    levelNumber: 2,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "",
    members: ["kick", "sick", "thick", "click", "pick", "lick", "stick"],
    traps: [],
    sentences: [
      { en: "I pick a thick stick.", vi: "Tôi nhặt một cành cây dày." },
      { en: "The sick cat can kick and lick.", vi: "Con mèo bị ốm biết đá và liếm." },
    ],
  },
  {
    pattern: "og",
    soundIpa: "/ɒɡ/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "k"],
    trapNote: "",
    members: ["dog", "frog", "fog", "log", "jog"],
    traps: [],
    sentences: [
      { en: "The dog and the frog sit on a log.", vi: "Con chó và con ếch ngồi trên một khúc gỗ." },
      { en: "They jog in the fog.", vi: "Chúng chạy bộ trong sương mù." },
    ],
  },
  {
    pattern: "op",
    soundIpa: "/ɒp/",
    levelNumber: 2,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "",
    members: ["stop", "shop", "top", "hop", "mop", "pop", "drop"],
    traps: [],
    sentences: [
      { en: "Stop and hop to the shop.", vi: "Dừng lại và nhảy đến cửa hàng." },
      { en: "Drop the mop on top.", vi: "Thả cây lau nhà lên trên." },
    ],
  },
  {
    pattern: "ock",
    soundIpa: "/ɒk/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "g"],
    trapNote: "",
    members: ["clock", "block", "sock", "rock", "lock", "dock"],
    traps: [],
    sentences: [
      { en: "The sock is on the clock.", vi: "Chiếc tất ở trên cái đồng hồ." },
      { en: "A block is on a rock by the dock.", vi: "Một khối gỗ nằm trên hòn đá cạnh bến tàu." },
    ],
  },
  {
    pattern: "uck",
    soundIpa: "/ʌk/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "",
    members: ["duck", "truck", "luck", "stuck", "tuck"],
    traps: [],
    sentences: [
      { en: "The duck is stuck in a truck.", vi: "Con vịt bị kẹt trong một chiếc xe tải." },
      { en: "What luck!", vi: "Thật may mắn!" },
    ],
  },
  {
    pattern: "ate",
    soundIpa: "/eɪt/",
    levelNumber: 3,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "Hai từ này cũng có chữ “ate” nhưng đọc khác: chocolate đọc là /ˈtʃɒklət/, pirate đọc là /ˈpaɪrət/. Nghe kỹ nhé!",
    members: ["late", "date", "plate", "skate", "gate"],
    traps: ["chocolate", "pirate"],
    sentences: [
      { en: "I skate to the gate on a date.", vi: "Tôi trượt ván đến cổng trong một buổi hẹn." },
      { en: "I am late, but my plate is big.", vi: "Tôi đến muộn, nhưng cái đĩa của tôi to." },
    ],
  },
  {
    pattern: "ame",
    soundIpa: "/eɪm/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "",
    members: ["name", "game", "same", "came", "frame", "flame"],
    traps: [],
    sentences: [
      { en: "The game has the same name.", vi: "Trò chơi có cùng một cái tên." },
      { en: "A flame came to the frame.", vi: "Một ngọn lửa bay đến cái khung." },
    ],
  },
  {
    pattern: "ice",
    soundIpa: "/aɪs/",
    levelNumber: 2,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "Hai từ này cũng có chữ “ice” nhưng đọc khác: juice đọc là /dʒuːs/, office đọc là /ˈɒfɪs/. Nghe kỹ nhé!",
    members: ["rice", "price", "mice", "nice", "dice", "slice", "twice"],
    traps: ["juice", "office"],
    sentences: [
      { en: "Nice mice eat rice twice.", vi: "Những chú chuột dễ thương ăn cơm hai lần." },
      { en: "The mice have the dice.", vi: "Những chú chuột có xúc xắc." },
    ],
  },
  {
    pattern: "eep",
    soundIpa: "/iːp/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "g"],
    trapNote: "",
    members: ["sheep", "sleep", "deep", "keep", "beep", "jeep"],
    traps: [],
    sentences: [
      { en: "A sheep can sleep in a deep jeep.", vi: "Con cừu có thể ngủ trong chiếc xe jeep sâu hoắm." },
      { en: "Beep, beep, keep out!", vi: "Bíp, bíp, tránh ra!" },
    ],
  },
  {
    pattern: "oat",
    soundIpa: "/əʊt/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "",
    members: ["goat", "boat", "coat", "float", "throat"],
    traps: [],
    sentences: [
      { en: "A goat is in a boat.", vi: "Một con dê ở trong một chiếc thuyền." },
      { en: "The boat can float and the goat has a coat.", vi: "Chiếc thuyền biết nổi và con dê có một cái áo khoác." },
    ],
  },
  {
    pattern: "ay",
    soundIpa: "/eɪ/",
    levelNumber: 2,
    buildRime: null,
    decoys: ["z", "v", "k"],
    trapNote: "",
    members: ["play", "say", "pay", "may", "day", "way", "stay", "tray"],
    traps: [],
    sentences: [
      { en: "I say, stay and play all day.", vi: "Tôi nói, hãy ở lại chơi cả ngày." },
      { en: "Let me pay for the tray.", vi: "Để tôi trả tiền cái khay nhé." },
    ],
  },
  {
    pattern: "ook",
    soundIpa: "/ʊk/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "",
    members: ["book", "look", "cook", "hook", "took", "shook"],
    traps: [],
    sentences: [
      { en: "I took a book and a hook to cook.", vi: "Tôi mang một quyển sách và một cái móc đi nấu ăn." },
      { en: "Look, the book shook.", vi: "Nhìn kìa, quyển sách đang rung." },
    ],
  },
  {
    pattern: "oon",
    soundIpa: "/uːn/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "",
    members: ["moon", "spoon", "balloon", "afternoon", "cartoon", "soon", "noon"],
    traps: [],
    sentences: [
      { en: "The moon is like a spoon at noon.", vi: "Mặt trăng giống cái thìa vào buổi trưa." },
      { en: "Soon we see a cartoon with a balloon.", vi: "Chẳng bao lâu chúng ta xem một phim hoạt hình có quả bóng bay." },
    ],
  },
  {
    pattern: "ow",
    soundIpa: "/əʊ/",
    levelNumber: 2,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "Hai từ này cũng có chữ “ow” nhưng đọc là /aʊ/, không phải /əʊ/: cow đọc là /kaʊ/, now đọc là /naʊ/. Nghe kỹ nhé!",
    members: ["snow", "slow", "low", "grow", "know", "throw", "blow", "show", "flow"],
    traps: ["cow", "now"],
    sentences: [
      { en: "I know it will snow, so go slow.", vi: "Tôi biết trời sắp có tuyết, nên hãy đi chậm." },
      { en: "We throw a ball in the snow.", vi: "Chúng tôi ném một quả bóng trong tuyết." },
    ],
  },
  {
    pattern: "all",
    soundIpa: "/ɔːl/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "",
    members: ["ball", "wall", "small", "tall", "fall", "call", "hall", "mall"],
    traps: [],
    sentences: [
      { en: "A small ball falls on the tall wall.", vi: "Một quả bóng nhỏ rơi lên bức tường cao." },
      { en: "Call us in the hall.", vi: "Hãy gọi chúng tôi ở đại sảnh." },
    ],
  },
  {
    pattern: "ing",
    soundIpa: "/ɪŋ/",
    levelNumber: 2,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "",
    members: ["sing", "ring", "king", "bring", "spring", "wing", "thing", "swing"],
    traps: [],
    sentences: [
      { en: "The king can sing and swing.", vi: "Nhà vua biết hát và đu đưa." },
      { en: "A bird with a wing brings spring.", vi: "Con chim có đôi cánh mang mùa xuân đến." },
    ],
  },
  {
    pattern: "ar",
    soundIpa: "/ɑː/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "g"],
    trapNote: "Ba từ này cũng có chữ “ar” nhưng đọc khác hẳn: bear đọc là /beə/, pear đọc là /peə/, ear đọc là /ɪə/. Nghe kỹ nhé!",
    members: ["car", "star", "far", "jar", "bar"],
    traps: ["bear", "pear", "ear"],
    sentences: [
      { en: "The car is far from the star.", vi: "Chiếc xe ở xa ngôi sao." },
      { en: "A jar is on a bar.", vi: "Một cái lọ nằm trên một thanh gỗ." },
    ],
  },
  {
    pattern: "ee",
    soundIpa: "/iː/",
    levelNumber: 1,
    buildRime: null,
    decoys: ["z", "v", "j"],
    trapNote: "Từ coffee cũng có chữ “ee” nhưng đọc là /ˈkɒfi/, không phải âm /iː/ như cả họ. Nghe kỹ nhé!",
    members: ["bee", "tree", "three", "knee", "see", "free"],
    traps: ["coffee"],
    sentences: [
      { en: "I see a bee in a tree.", vi: "Tôi thấy một con ong trên cái cây." },
      { en: "The bee sits on my knee.", vi: "Con ong đậu trên đầu gối của tôi." },
    ],
  },
];
